import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, BadgeCheck, Calculator, Loader2, Sparkles, UserPen, Lightbulb } from "lucide-react";
import { t } from "../lib/i18n";

/** Translate plain-string children; leave elements untouched. */
export const tr = (v: ReactNode): ReactNode => (typeof v === "string" ? t(v) : v);

export const cx = (...c: (string | false | null | undefined)[]) => c.filter(Boolean).join(" ");

export const SIZE = {
  md: "px-4 py-2.5 text-sm rounded-xl",
  sm: "px-3 py-1.5 text-xs rounded-lg",
  lg: "px-6 py-3.5 text-base rounded-xl",
};

export function Card({ children, className, title, subtitle, action, icon }: {
  children?: ReactNode; className?: string; title?: ReactNode; subtitle?: ReactNode; action?: ReactNode; icon?: ReactNode;
}) {
  return (
    <section className={cx("card p-5", className)}>
      {(title || action) && (
        <div className="mb-4 flex items-start justify-between gap-3">
          <div className="flex items-start gap-3">
            {icon && <div className="mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600">{icon}</div>}
            <div>
              {title && <h3 className="text-base font-bold text-slate-900">{tr(title)}</h3>}
              {subtitle && <p className="mt-0.5 text-sm text-slate-500">{tr(subtitle)}</p>}
            </div>
          </div>
          {action}
        </div>
      )}
      {children}
    </section>
  );
}

type Kind = "ai" | "user" | "calc" | "verified" | "unverified" | "assumption";
const KIND: Record<Kind, { cls: string; label: string; icon: ReactNode; title: string }> = {
  ai: {
    cls: "bg-violet-50 text-violet-700 ring-violet-200",
    label: "AI Estimate",
    icon: <Sparkles className="h-3 w-3" />,
    title: "Generated by AI from your inputs. Not verified real-world data.",
  },
  user: { cls: "bg-sky-50 text-sky-700 ring-sky-200", label: "User Input", icon: <UserPen className="h-3 w-3" />, title: "A value you entered." },
  calc: {
    cls: "bg-emerald-50 text-emerald-700 ring-emerald-200",
    label: "Calculated",
    icon: <Calculator className="h-3 w-3" />,
    title: "Calculated with a formula from the inputs shown.",
  },
  verified: {
    cls: "bg-green-50 text-green-700 ring-green-200",
    label: "Live listing",
    icon: <BadgeCheck className="h-3 w-3" />,
    title: "Retrieved from a live map/business data source. Contact before purchasing.",
  },
  unverified: {
    cls: "bg-amber-50 text-amber-800 ring-amber-200",
    label: "AI-suggested source — verify before purchasing",
    icon: <AlertTriangle className="h-3 w-3" />,
    title: "Suggested by AI, not from a live data source.",
  },
  assumption: {
    cls: "bg-amber-50 text-amber-800 ring-amber-200",
    label: "AI Assumption",
    icon: <Lightbulb className="h-3 w-3" />,
    title: "An AI assumption about typical businesses of this type — not verified.",
  },
};

export function Tag({ kind, label, className }: { kind: Kind; label?: string; className?: string }) {
  const k = KIND[kind];
  return (
    <span title={t(k.title)} className={cx("inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-semibold ring-1 ring-inset", k.cls, className)}>
      {k.icon}
      {t(label || k.label)}
    </span>
  );
}

export function Pill({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <span className={cx("inline-flex items-center gap-1 whitespace-nowrap rounded-full px-2.5 py-0.5 text-xs font-semibold ring-1 ring-inset", className || "bg-slate-100 text-slate-700 ring-slate-200")}>
      {children}
    </span>
  );
}

export function Stat({ label, value, sub, tag, icon, tone }: {
  label: string; value: ReactNode; sub?: ReactNode; tag?: Kind; icon?: ReactNode; tone?: string;
}) {
  return (
    <div className="card p-4">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-slate-500">
          {icon}
          {t(label)}
        </div>
        {tag && <Tag kind={tag} />}
      </div>
      <div className={cx("mt-2 font-display text-2xl font-extrabold text-slate-900", tone)}>{value}</div>
      {sub && <div className="mt-1 text-xs text-slate-500">{tr(sub)}</div>}
    </div>
  );
}

export function PageHeader({ title, subtitle, actions, eyebrow }: { title: ReactNode; subtitle?: ReactNode; actions?: ReactNode; eyebrow?: ReactNode }) {
  return (
    <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
      <div>
        {eyebrow && <div className="mb-1 text-xs font-semibold uppercase tracking-wider text-indigo-600">{tr(eyebrow)}</div>}
        <h1 className="font-display text-2xl font-extrabold tracking-tight text-slate-900 md:text-3xl">{tr(title)}</h1>
        {subtitle && <p className="mt-1.5 max-w-3xl text-sm text-slate-500">{tr(subtitle)}</p>}
      </div>
      {actions && <div className="flex flex-wrap gap-2">{actions}</div>}
    </div>
  );
}

export function Spinner({ className }: { className?: string }) {
  return <Loader2 className={cx("h-4 w-4 animate-spin", className)} />;
}

export function LoadingBlock({ label = "Loading…" }: { label?: string }) {
  label = t(label);
  return (
    <div className="grid place-items-center py-24 text-slate-500">
      <div className="flex items-center gap-3">
        <Spinner className="h-5 w-5 text-indigo-600" /> {label}
      </div>
    </div>
  );
}

export function EmptyState({ title, body, action, icon }: { title: string; body?: ReactNode; action?: ReactNode; icon?: ReactNode }) {
  return (
    <div className="card bg-hero grid place-items-center px-6 py-16 text-center">
      <div className="mx-auto max-w-md">
        <div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white shadow-lg shadow-indigo-500/30">
          {icon || <Sparkles className="h-7 w-7" />}
        </div>
        <h2 className="font-display text-xl font-extrabold text-slate-900">{t(title)}</h2>
        {body && <p className="mt-2 text-sm text-slate-500">{tr(body)}</p>}
        {action && <div className="mt-6 flex justify-center gap-2">{action}</div>}
      </div>
    </div>
  );
}

export function ErrorBox({ title, children, actions }: { title: string; children?: ReactNode; actions?: ReactNode }) {
  return (
    <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-rose-900">
      <div className="flex items-start gap-3">
        <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-rose-600" />
        <div className="flex-1">
          <div className="font-semibold">{t(title)}</div>
          {children && <div className="mt-1 text-sm text-rose-800/90">{children}</div>}
          {actions && <div className="mt-4 flex flex-wrap gap-2">{actions}</div>}
        </div>
      </div>
    </div>
  );
}

export function Notice({ children, tone = "info" }: { children: ReactNode; tone?: "info" | "warn" | "ai" }) {
  const cls =
    tone === "warn"
      ? "border-amber-200 bg-amber-50 text-amber-900"
      : tone === "ai"
        ? "border-violet-200 bg-violet-50 text-violet-900"
        : "border-sky-200 bg-sky-50 text-sky-900";
  return <div className={cx("rounded-xl border px-4 py-3 text-sm", cls)}>{children}</div>;
}

export function BulletList({ items, className, icon }: { items?: string[]; className?: string; icon?: ReactNode }) {
  if (!items?.length) return <p className="text-sm text-slate-400">{t("Not provided.")}</p>;
  return (
    <ul className={cx("space-y-2", className)}>
      {items.map((t, i) => (
        <li key={i} className="flex gap-2.5 text-sm leading-relaxed text-slate-700">
          <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-indigo-400">{icon}</span>
          <span>{t}</span>
        </li>
      ))}
    </ul>
  );
}

/** Wraps pages that need a completed analysis for the current business. */
export function NeedsAnalysis({ ctx, children }: { ctx: { loading: boolean; ai: any; analysis: any; idea: any; error: string | null }; children: ReactNode }) {
  if (ctx.loading) return <LoadingBlock label="Loading your business…" />;
  if (ctx.error) return <ErrorBox title={t("Could not load this business")}>{ctx.error}</ErrorBox>;
  if (!ctx.idea) {
    return (
      <EmptyState
        title={t("No Business Idea Analyzed Yet")}
        body={t("Describe your business idea and Startup Sense will run a real AI analysis for your location and budget.")}
        action={<Link to="/new" className={cx("btn-primary", SIZE.md)}><Sparkles className="h-4 w-4" /> {t("Analyze Your First Idea")}</Link>}
      />
    );
  }
  if (ctx.analysis?.status === "queued" || ctx.analysis?.status === "running") {
    return (
      <EmptyState
        title={t("Analysis in progress: {name}", { name: ctx.idea.businessName })}
        body={t("The AI is still working on this business. Results will appear here as soon as it finishes.")}
        icon={<Spinner className="h-7 w-7" />}
        action={<Link to={`/analyzing/${ctx.idea.id}?analysisId=${ctx.analysis.id}`} className={cx("btn-primary", SIZE.md)}>{t("View progress")}</Link>}
      />
    );
  }
  if (!ctx.ai) {
    return (
      <ErrorBox
        title={t("AI analysis could not be completed.")}
        actions={
          <>
            <Link to={`/analyzing/${ctx.idea.id}?retry=1`} className={cx("btn-primary", SIZE.md)}>{t("Retry Analysis")}</Link>
            <Link to="/new" className={cx("btn-secondary", SIZE.md)}>{t("Back to New Idea")}</Link>
          </>
        }
      >
        {t("The latest analysis for “{name}” did not finish.", { name: ctx.idea.businessName })} {ctx.analysis?.error ? <span className="block mt-1 text-xs opacity-80">{ctx.analysis.error}</span> : null}
      </ErrorBox>
    );
  }
  return <>{children}</>;
}

export function ScoreRing({ score, size = 120 }: { score: number; size?: number }) {
  const r = (size - 14) / 2;
  const c = 2 * Math.PI * r;
  const pct = Math.max(0, Math.min(1, score / 10));
  const color = score >= 7.5 ? "#10b981" : score >= 6 ? "#6366f1" : score >= 4.5 ? "#f59e0b" : "#f43f5e";
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} role="img" aria-label={t("AI validation score {score} out of 10", { score })}>
      <circle cx={size / 2} cy={size / 2} r={r} stroke="#e2e8f0" strokeWidth="10" fill="none" />
      <circle
        cx={size / 2} cy={size / 2} r={r} stroke={color} strokeWidth="10" fill="none" strokeLinecap="round"
        strokeDasharray={`${c * pct} ${c}`} transform={`rotate(-90 ${size / 2} ${size / 2})`}
      />
      <text x="50%" y="48%" textAnchor="middle" dominantBaseline="middle" className="font-display" fontSize={size / 4} fontWeight="800" fill="#0f172a">
        {score.toFixed(1)}
      </text>
      <text x="50%" y="68%" textAnchor="middle" fontSize={size / 11} fill="#64748b">/ 10</text>
    </svg>
  );
}

export function MiniBar({ value, max = 10, color = "bg-indigo-500" }: { value: number; max?: number; color?: string }) {
  return (
    <div className="h-2 w-full overflow-hidden rounded-full bg-slate-100">
      <div className={cx("h-full rounded-full", color)} style={{ width: `${Math.max(0, Math.min(100, (value / max) * 100))}%` }} />
    </div>
  );
}
