// Real location data: geocoding + nearby business search.
// Sources: Google Places API (only when GOOGLE_MAPS_API_KEY is set) and OpenStreetMap (Nominatim + Overpass).
// Nothing here is generated by AI: every listing comes from a live data source.
import { env } from "./http.mts";
import { cleanKeywords, cleanOsmTags } from "./finance.mts";

const UA = "StartupSense/1.0 (AI business validator; https://startup-sense-ai.netlify.app)";
const OVERPASS = [
  "https://overpass-api.de/api/interpreter",
  "https://overpass.kumi.systems/api/interpreter",
  "https://overpass.private.coffee/api/interpreter",
];
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

export interface GeoPoint {
  lat: number;
  lng: number;
  displayName: string;
  source: "Google Geocoding" | "OpenStreetMap Nominatim";
  precision: "area" | "city";
}

export function haversineKm(a: { lat: number; lng: number }, b: { lat: number; lng: number }) {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const s =
    Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) * Math.cos((b.lat * Math.PI) / 180) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}

async function fetchJson(url: string, init: RequestInit = {}, timeoutMs = 20_000) {
  const res = await fetch(url, { ...init, signal: AbortSignal.timeout(timeoutMs) });
  if (!res.ok) throw new Error(`${new URL(url).host} HTTP ${res.status}`);
  return res.json();
}

export async function geocode(loc: { area?: string; city: string; state?: string; country: string }): Promise<GeoPoint | null> {
  const gkey = env("GOOGLE_MAPS_API_KEY");
  const full = [loc.area, loc.city, loc.state, loc.country].filter(Boolean).join(", ");
  const cityOnly = [loc.city, loc.state, loc.country].filter(Boolean).join(", ");
  if (gkey) {
    try {
      const d: any = await fetchJson(
        `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(full)}&key=${gkey}`
      );
      const r = d?.results?.[0];
      if (r?.geometry?.location) {
        return {
          lat: r.geometry.location.lat,
          lng: r.geometry.location.lng,
          displayName: r.formatted_address,
          source: "Google Geocoding",
          precision: loc.area ? "area" : "city",
        };
      }
    } catch (e) {
      console.warn("Google geocode failed, falling back to Nominatim", e);
    }
  }
  const attempts: [string, "area" | "city"][] = loc.area ? [[full, "area"], [cityOnly, "city"]] : [[cityOnly, "city"]];
  for (const [q, precision] of attempts) {
    try {
      const d: any = await fetchJson(
        `https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`,
        { headers: { "user-agent": UA, "accept-language": "en" } }
      );
      if (Array.isArray(d) && d[0]) {
        return {
          lat: Number(d[0].lat),
          lng: Number(d[0].lon),
          displayName: d[0].display_name,
          source: "OpenStreetMap Nominatim",
          precision,
        };
      }
    } catch (e) {
      console.warn("Nominatim geocode failed", e);
    }
    await sleep(1100);
  }
  return null;
}

async function reverseGeocode(lat: number, lng: number): Promise<string | null> {
  try {
    const d: any = await fetchJson(
      `https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=17&lat=${lat}&lon=${lng}`,
      { headers: { "user-agent": UA, "accept-language": "en" } },
      10_000
    );
    return d?.display_name || null;
  } catch {
    return null;
  }
}

export interface SearchTarget {
  name: string; // material or competitor type label
  keywords: string[];
  osmTags: string[];
}

export interface PlaceResult {
  id: string;
  source: "Google Places" | "OpenStreetMap";
  name: string;
  supplierType: string;
  matchedFor: string[]; // which materials / targets it matched
  matchReason: string;
  relevance: number;
  address: string | null;
  addressApproximate: boolean;
  locality: string | null;
  lat: number;
  lng: number;
  distanceKm: number;
  phone: string | null;
  email: string | null;
  website: string | null;
  openingHours: string | null;
  openNow: boolean | null;
  rating: number | null;
  ratingCount: number | null;
  price: null; // no verified price source is available — never estimated
  products: string | null;
  sourceUrl: string | null;
}

const TYPE_RULES: [string, RegExp][] = [
  ["Dealers", /\b(dealer|dealers|dealership|authori[sz]ed|showroom)\b/i],
  ["Distributors", /\b(distribut\w*|agency|agencies|c\s*&\s*f|stockist)\b/i],
  ["Wholesalers", /\b(wholesale\w*|mandi|bulk)\b/i],
  ["Factories", /\b(factory|plant|mill|mills|unit)\b/i],
  ["Manufacturers", /\b(manufactur\w*|industries|industry|udyog|products|pvt\.?\s*ltd|private limited|ltd|works|fabricat\w*)\b/i],
  ["Raw Material Suppliers", /\b(supplier|suppliers|supply|traders|trading|merchant|merchants|raw|materials?|depot|mart|store|centre|center|house)\b/i],
];

function classify(name: string, tags: Record<string, string>): string {
  if (tags.shop === "wholesale") return "Wholesalers";
  for (const [t, re] of TYPE_RULES) if (re.test(name)) return t;
  if (tags.man_made === "works" || tags.industrial || tags.landuse === "industrial") return "Manufacturers";
  if (tags.craft) return "Manufacturers";
  if (tags.shop === "car" || tags.shop === "motorcycle") return "Dealers";
  if (tags.shop) return "Raw Material Suppliers";
  return "Unclassified";
}

const EXCLUDED_AMENITIES = new Set([
  "school", "college", "university", "kindergarten", "place_of_worship", "hospital", "clinic", "doctors",
  "bank", "atm", "restaurant", "cafe", "fast_food", "pharmacy", "police", "townhall", "bus_station", "parking",
]);

function escapeRe(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\"]/g, "\\$&");
}

function osmAddress(t: Record<string, string>): { address: string | null; locality: string | null } {
  if (t["addr:full"]) return { address: t["addr:full"], locality: t["addr:suburb"] || t["addr:city"] || null };
  const parts = [
    [t["addr:housenumber"], t["addr:street"]].filter(Boolean).join(" "),
    t["addr:place"], t["addr:suburb"] || t["addr:neighbourhood"] || t["addr:quarter"],
    t["addr:city"] || t["addr:district"], t["addr:postcode"],
  ].filter(Boolean);
  const locality = t["addr:suburb"] || t["addr:neighbourhood"] || t["addr:city"] || null;
  return { address: parts.length >= 2 ? parts.join(", ") : null, locality };
}

async function overpass(query: string): Promise<any[]> {
  let lastErr: unknown;
  for (const ep of OVERPASS) {
    try {
      const res = await fetch(ep, {
        method: "POST",
        headers: { "content-type": "application/x-www-form-urlencoded", "user-agent": UA },
        body: "data=" + encodeURIComponent(query),
        signal: AbortSignal.timeout(40_000),
      });
      if (!res.ok) throw new Error(`Overpass ${new URL(ep).host} HTTP ${res.status}`);
      const d: any = await res.json();
      return Array.isArray(d?.elements) ? d.elements : [];
    } catch (e) {
      lastErr = e;
      console.warn("Overpass endpoint failed", ep, String(e));
    }
  }
  throw lastErr ?? new Error("Overpass unavailable");
}

export async function searchOSM(center: { lat: number; lng: number }, targets: SearchTarget[], radiusKm: number): Promise<PlaceResult[]> {
  const R = Math.round(Math.min(Math.max(radiusKm, 1), 60) * 1000);
  const around = `(around:${R},${center.lat.toFixed(5)},${center.lng.toFixed(5)})`;
  const clauses: string[] = [];
  const kwAll = new Set<string>();
  const tagAll = new Set<string>();
  for (const t of targets) {
    cleanKeywords(t.keywords).forEach((k) => kwAll.add(k));
    cleanOsmTags(t.osmTags).forEach((k) => tagAll.add(k));
  }
  if (kwAll.size) {
    const re = Array.from(kwAll).map(escapeRe).join("|");
    clauses.push(`nwr["name"~"${re}",i]${around};`);
    clauses.push(`nwr["products"~"${re}",i]${around};`);
    clauses.push(`nwr["description"~"${re}",i]["name"]${around};`);
  }
  for (const tag of tagAll) {
    const [k, v] = tag.split("=");
    clauses.push(`nwr["${k}"="${v.replace(/"/g, "")}"]["name"]${around};`);
  }
  if (!clauses.length) return [];
  const query = `[out:json][timeout:35];(${clauses.join("")});out center tags 300;`;
  const elements = await overpass(query);

  const results: PlaceResult[] = [];
  for (const el of elements) {
    const t: Record<string, string> = el.tags || {};
    const name = t.name || t["name:en"];
    if (!name) continue;
    if (t.amenity && EXCLUDED_AMENITIES.has(t.amenity)) continue;
    const lat = el.lat ?? el.center?.lat;
    const lng = el.lon ?? el.center?.lon;
    if (typeof lat !== "number" || typeof lng !== "number") continue;
    const hay = `${name} ${t.products || ""} ${t.description || ""}`.toLowerCase();

    const matchedFor: string[] = [];
    const reasons: string[] = [];
    let relevance = 0;
    for (const target of targets) {
      const kws = cleanKeywords(target.keywords).filter((k) => hay.includes(k));
      const tags = cleanOsmTags(target.osmTags).filter((tag) => {
        const [k, v] = tag.split("=");
        return t[k] === v;
      });
      if (kws.length || tags.length) {
        matchedFor.push(target.name);
        relevance += kws.reduce((s, k) => s + (k.includes(" ") ? 4 : 3), 0) + tags.length * 2;
        if (kws.length) reasons.push(`name/products mention "${kws[0]}"`);
        else reasons.push(`mapped as ${tags[0]}`);
      }
    }
    if (!matchedFor.length) continue;
    if (t.shop === "wholesale" || t.industrial || t.man_made === "works") relevance += 1;
    const { address, locality } = osmAddress(t);
    const phone = t.phone || t["contact:phone"] || t["contact:mobile"] || null;
    results.push({
      id: `osm:${el.type}/${el.id}`,
      source: "OpenStreetMap",
      name,
      supplierType: classify(name, t),
      matchedFor,
      matchReason: Array.from(new Set(reasons)).slice(0, 2).join("; "),
      relevance,
      address,
      addressApproximate: false,
      locality,
      lat,
      lng,
      distanceKm: Math.round(haversineKm(center, { lat, lng }) * 10) / 10,
      phone: phone ? phone.split(";")[0].trim() : null,
      email: t.email || t["contact:email"] || null,
      website: t.website || t["contact:website"] || t.url || null,
      openingHours: t.opening_hours || null,
      openNow: null,
      rating: null,
      ratingCount: null,
      price: null,
      products: t.products || null,
      sourceUrl: `https://www.openstreetmap.org/${el.type}/${el.id}`,
    });
  }
  return results;
}

export async function searchGoogle(
  center: { lat: number; lng: number },
  targets: SearchTarget[],
  radiusKm: number,
  city: string,
  kind: "supplier" | "competitor"
): Promise<PlaceResult[]> {
  const key = env("GOOGLE_MAPS_API_KEY");
  if (!key) return [];
  const out: PlaceResult[] = [];
  for (const target of targets.slice(0, 7)) {
    const textQuery = kind === "supplier" ? `${target.name} supplier wholesaler manufacturer in ${city}` : `${target.name} in ${city}`;
    const res = await fetch("https://places.googleapis.com/v1/places:searchText", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "X-Goog-Api-Key": key,
        "X-Goog-FieldMask": [
          "places.id", "places.displayName", "places.formattedAddress", "places.shortFormattedAddress", "places.location",
          "places.nationalPhoneNumber", "places.internationalPhoneNumber", "places.websiteUri", "places.rating",
          "places.userRatingCount", "places.currentOpeningHours.openNow", "places.regularOpeningHours.weekdayDescriptions",
          "places.primaryTypeDisplayName", "places.googleMapsUri", "places.businessStatus",
        ].join(","),
      },
      body: JSON.stringify({
        textQuery,
        maxResultCount: 20,
        locationBias: {
          circle: { center: { latitude: center.lat, longitude: center.lng }, radius: Math.min(50000, radiusKm * 1000) },
        },
      }),
      signal: AbortSignal.timeout(20_000),
    });
    if (!res.ok) throw new Error(`Google Places HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const d: any = await res.json();
    for (const p of d.places || []) {
      if (p.businessStatus && p.businessStatus !== "OPERATIONAL") continue;
      const lat = p.location?.latitude;
      const lng = p.location?.longitude;
      if (typeof lat !== "number") continue;
      const name = p.displayName?.text || "";
      const distanceKm = Math.round(haversineKm(center, { lat, lng }) * 10) / 10;
      if (distanceKm > radiusKm * 1.5) continue;
      out.push({
        id: `google:${p.id}`,
        source: "Google Places",
        name,
        supplierType: classify(`${name} ${p.primaryTypeDisplayName?.text || ""}`, {}),
        matchedFor: [target.name],
        matchReason: `Google Places result for "${textQuery}"${p.primaryTypeDisplayName?.text ? ` · ${p.primaryTypeDisplayName.text}` : ""}`,
        relevance: 3,
        address: p.formattedAddress || null,
        addressApproximate: false,
        locality: p.shortFormattedAddress || null,
        lat,
        lng,
        distanceKm,
        phone: p.nationalPhoneNumber || p.internationalPhoneNumber || null,
        email: null,
        website: p.websiteUri || null,
        openingHours: p.regularOpeningHours?.weekdayDescriptions?.join(" | ") || null,
        openNow: typeof p.currentOpeningHours?.openNow === "boolean" ? p.currentOpeningHours.openNow : null,
        rating: typeof p.rating === "number" ? p.rating : null,
        ratingCount: typeof p.userRatingCount === "number" ? p.userRatingCount : null,
        price: null,
        products: null,
        sourceUrl: p.googleMapsUri || null,
      });
    }
  }
  return out;
}

function normName(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

/** Merge + dedupe, fill missing addresses by reverse geocoding (clearly flagged as approximate), sort by distance. */
export async function findNearby(opts: {
  center: { lat: number; lng: number };
  targets: SearchTarget[];
  radiusKm: number;
  city: string;
  kind: "supplier" | "competitor";
  maxResults?: number;
}) {
  const sources: string[] = [];
  const errors: string[] = [];
  let all: PlaceResult[] = [];

  if (env("GOOGLE_MAPS_API_KEY")) {
    try {
      const g = await searchGoogle(opts.center, opts.targets, opts.radiusKm, opts.city, opts.kind);
      all.push(...g);
      sources.push("Google Places");
    } catch (e) {
      errors.push(`Google Places: ${String((e as Error)?.message || e)}`);
    }
  }
  try {
    const o = await searchOSM(opts.center, opts.targets, opts.radiusKm);
    all.push(...o);
    sources.push("OpenStreetMap");
  } catch (e) {
    errors.push(`OpenStreetMap: ${String((e as Error)?.message || e)}`);
  }

  // dedupe: same normalised name within 300 m → keep the richer record (Google first)
  const kept: PlaceResult[] = [];
  for (const r of all) {
    const dup = kept.find(
      (k) => normName(k.name) === normName(r.name) && haversineKm(k, r) < 0.3
    );
    if (dup) {
      dup.matchedFor = Array.from(new Set([...dup.matchedFor, ...r.matchedFor]));
      dup.phone ||= r.phone;
      dup.website ||= r.website;
      dup.email ||= r.email;
      dup.openingHours ||= r.openingHours;
      dup.address ||= r.address;
      continue;
    }
    kept.push(r);
  }
  kept.sort((a, b) => a.distanceKm - b.distanceKm);
  const limited = kept.slice(0, opts.maxResults ?? 60);

  // Reverse-geocode a limited number of listings without an address (Nominatim: max 1 req/s).
  let lookups = 0;
  for (const r of limited) {
    if (r.address || lookups >= 12) continue;
    lookups++;
    const a = await reverseGeocode(r.lat, r.lng);
    if (a) {
      r.address = a;
      r.addressApproximate = true;
    }
    await sleep(1100);
  }

  const available = sources.length > 0;
  return {
    status: available ? (errors.length ? "partial" : "ok") : "unavailable",
    sources,
    errors,
    results: limited,
    radiusKm: opts.radiusKm,
    center: opts.center,
    searchedAt: new Date().toISOString(),
    googleEnabled: Boolean(env("GOOGLE_MAPS_API_KEY")),
  };
}
